version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - chroma-data:/app/chroma # Persistent Chroma db storage
    environment:
      - PHOENIX_COLLECTOR_ENDPOINT=http://phoenix:6006
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - PYTHONUNBUFFERED=1
    depends_on:
      ollama:
        condition: service_healthy
      phoenix:
        condition: service_started
    networks:
      - rag-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    # command:  run llama3.2:3b
    # entrypoint:  ollama run llama3.2:3b
    post_start:
      - command : "ollama run llama3.2:3b"
    ports:
      - "11434:11434"
    # command: >
    #   ollama run llama3.2:3b
    # entrypoint:  ollama run llama3.2:3b
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    tty: true
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
      - "4317:4317"
    # command: phoenix serve
    networks:
      - rag-network
    restart: unless-stopped

volumes:
  ollama-data:
  chroma-data:


networks:
  rag-network:
    driver: bridge
